### PR TITLE
feature/import declaration (#31)

### PR DESCRIPTION
**Pull request by GabeMedrash**
This PR extends the plugin to be able to operate directly on es6 ImportDeclarations (specifically, default imports). It's in reference to issue #31. The substantive changes proposed are:

**1. Transformation of test fixtures**
Specifically prevent `babel.transformFileSync` from inheriting project-level babel configuration (`babelrc: false`), and remove `transform-es2015-modules-commonjs` from list of plugins applied to test fixtures.

**2. Visitor method to operate on default imports**
Replace `ImportDeclaration` visitor method with `ImportDefaultSpecifier` to operate directly on statements like `import styles from './style.css'` without relying on those statements being transpiled into `var styles = require('./style.css')`.

Let me know what you think; happy to continue shaping this if you have comments regarding my approach.

Thanks!

### CODE REVIEW

**Comment by michalkvasnicak** [comment]
@GabeMedrash thank you very much 👍 I'll take a look next week, sorry about that.

**Comment by michalkvasnicak** [comment]
@GabeMedrash great work 🥇  It seems that it is backward compatible so we can release it as 1.2.0

**Comment by michalkvasnicak** [comment]
@GabeMedrash  Thank you 👍  👏

**Comment by michalkvasnicak** [comment]
Released as `1.2.0`

**Comment by GabeMedrash** [comment]
Thanks @michalkvasnicak!

**Pull request merged**
