### PR TITLE
Prevent caching CSS when in development mode

### PR DESCRIPTION
**Pull request by pronebird**
Fixes issue #33

### CODE REVIEW

**Comment by michalkvasnicak** [comment]
I think there should be change in writing logic, because now it is appending to css file. So it should do something like this.

if `devMode` is enabled, it should completely rewrite css file, otherwise it should append.

**Comment by michalkvasnicak** [comment]
And there is another thing to solve, we have to send all css contents to writeCss function because now it accepts only current transpiled css file and not all the previous css files.

**Comment by pronebird** [comment]
I am testing with single CSS file and combined CSS is always overwritten.

**Comment by michalkvasnicak** [comment]
It is overwriting file if there is only 1 css file otherwise it is appending and this causes tests to fail.

**Comment by pronebird** [comment]
I see, you're right. Let me see what I can do about it.

**Comment by pronebird** [comment]
If I run `babel --watch --skip-initial-build` it does not process files therefore changes to single file pretty much results in overwrite of entire CSS with the rules of changed CSS file. 

I skip initial build because there is no way to know when babel --watch finished generating file structure. Therefore I run babel twice, first time to generate file structure, after run I run electron app + `babel --watch`

**Comment by michalkvasnicak** [comment]
I think that we could solve regeneration of whole combined css file.

We could always rewrite whole combined css file but I am not sure what impact it'll have on performance of plugin. Maybe we can do checks in cache not only by filename but hash of contents for example? Then we'll know if we need to overwrite the whole combined css filed or just keep it as is because contents haven't changed.

**Comment by michalkvasnicak** [comment]
So in non `devMode` we'll keep the old logic and in `devMode` we will check contents too and rewrite css only if the css content is new or changed.

**Comment by pronebird** [comment]
Another option would be to always append but mark each entry in combined CSS somehow so we could strip out old rules before appending new ones. 

Performance wise this would be much faster then looping through all styles and generating combined CSS. This should also address my case with `--skip-initial-build`.

**Comment by michalkvasnicak** [comment]
Yeah but you'll end up with rewriting file anyway because if the string you want to strip is in the middle of the combined CSS file you don't have a way to strip it. 

So maybe something like, if the file is new append otherwise strip and rewrite. And we could keep the generated CSS in memory too.

**Comment by michalkvasnicak** [comment]
Closing, you can try `next` version (#38).

**Pull request closed without merging**
