### PR TITLE
docs(readme) example code

### PR DESCRIPTION
**Pull request by pixelass**
Changed an example since it had syntax errors and suggested a wrong pattern.

### CODE REVIEW

**Comment by michalkvasnicak** [comment]
@pixelass what was the problem with pattern `"[path]/[name].css"`? 

`[path]` should preserve directory structure of css files. But if this works without `[name]` then there is a bug we need to resolve. Because `[path]` should contain only path to file without filename.

I think you found a bug in this feature and now it's not necessary to update README but to fix this bug :)

**Comment by michalkvasnicak** [comment]
Thank you :) I'm closing this as this will be resolved in #25.

**Comment by pixelass** [comment]
Hah.. glad to help. shouldn't the example use valid JSON format though? (quotes)

**Comment by michalkvasnicak** [comment]
@pixelass yes, documentation is fixed in #25  :)

**Pull request closed without merging**
